# Generated by Django 6.0.8 on 2026-08-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_payment_mpesa_code_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='amount_expected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
