# Generated by Django 6.0.8 on 2026-08-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_payment_checkout_request_id_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
