# Generated by Django 6.0.8 on 2026-08-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_beneficiary_is_active_beneficiary_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Family Contribution System', max_length=100)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
