# Generated by Django 6.0.8 on 2026-08-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
