# Generated by Django 6.0.8 on 2026-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_payment_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_consumer_key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_consumer_secret',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_passkey',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
