# Generated by Django 6.0.8 on 2026-08-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_payment_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
