# Generated by Django 6.0.8 on 2026-08-12 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_payment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for this person each contribution.', max_digits=10)),
                ('frequency', models.CharField(choices=[('TWICE_WEEKLY', 'Twice a week'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='TWICE_WEEKLY', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_obligations', to='members.beneficiary')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='members.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_type', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20)),
                ('interest_value', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank')], default='Cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='members.loan')),
            ],
        ),
    ]
